export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST';
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_FAIL = 'CREATE_ORDER_FAIL';

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST';
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS';
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL';

export const DELETE_ORDER_REQUEST = 'DELETE_ORDER_REQUEST';
export const DELETE_ORDER_SUCCESS = 'DELETE_ORDER_SUCCESS';
export const DELETE_ORDER_FAIL = 'DELETE_ORDER_FAIL';

export const ORDER_TO_PAID_REQUEST = 'ORDER_TO_PAID_REQUEST';
export const ORDER_TO_PAID_SUCCESS = 'ORDER_TO_PAID_SUCCESS';
export const ORDER_TO_PAID_FAIL = 'ORDER_TO_PAID_FAIL';
export const ORDER_TO_PAID_RESET = 'ORDER_TO_PAID_RESET';

export const LIST_MY_ORDERS_REQUEST = 'LIST_MY_ORDERS_REQUEST';
export const LIST_MY_ORDERS_SUCCESS = 'LIST_MY_ORDERS_SUCCESS';
export const LIST_MY_ORDERS_FAIL = 'LIST_MY_ORDERS_FAIL';
export const LIST_MY_ORDERS_RESET = 'LIST_MY_ORDERS_RESET';

export const ADMIN_GET_ALL_ORDERS_REQUEST = 'ADMIN_GET_ALL_ORDERS_REQUEST';
export const ADMIN_GET_ALL_ORDERS_SUCCESS = 'ADMIN_GET_ALL_ORDERS_SUCCESS';
export const ADMIN_GET_ALL_ORDERS_FAIL = 'ADMIN_GET_ALL_ORDERS_FAIL';

export const ADMIN_OUT_FOR_DELIVERY_REQUEST = 'ADMIN_OUT_FOR_DELIVERY_REQUEST';
export const ADMIN_OUT_FOR_DELIVERY_SUCCESS = 'ADMIN_OUT_FOR_DELIVERY_SUCCESS';
export const ADMIN_OUT_FOR_DELIVERY_FAIL = 'ADMIN_OUT_FOR_DELIVERY_FAIL';
export const ADMIN_OUT_FOR_DELIVERY_RESET = 'ADMIN_OUT_FOR_DELIVERY_RESET';
