export const GET_POST_ITEM_REQUEST = 'GET_POST_ITEM_REQUEST';
export const GET_POST_ITEM_SUCCESS = 'GET_POST_ITEM_SUCCESS';
export const GET_POST_ITEM_FAIL = 'GET_POST_ITEM_FAIL';
export const GET_POST_ITEM_RESET = 'GET_POST_ITEM_RESET';

export const GET_POSTS_REQUEST = 'GET_POSTS_REQUEST';
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const GET_POSTS_FAIL = 'GET_POSTS_FAIL';
export const GET_POSTS_RESET = 'GET_POSTS_RESET';

export const UPDATE_LIKES_REQUEST = 'UPDATE_LIKES_REQUEST';
export const UPDATE_LIKES_SUCCESS = 'UPDATE_LIKES_SUCCESS';
export const UPDATE_LIKES_FAIL = 'UPDATE_LIKES_FAIL';

export const UPDATE_DISLIKES_REQUEST = 'UPDATE_DISLIKES_REQUEST';
export const UPDATE_DISLIKES_SUCCESS = 'UPDATE_DISLIKES_SUCCESS';
export const UPDATE_DISLIKES_FAIL = 'UPDATE_DISLIKES_FAIL';

export const ADD_POST_REQUEST = 'ADD_POST_REQUEST';
export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS';
export const ADD_POST_FAIL = 'ADD_POST_FAIL';

export const DELETE_POST_REQUEST = 'DELETE_POST_REQUEST';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const DELETE_POST_FAIL = 'DELETE_POST_FAIL';

export const ADD_COMMENT_REQUEST = 'ADD_COMMENT_REQUEST';
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';
export const ADD_COMMENT_FAIL = 'ADD_COMMENT_FAIL';

export const DELETE_COMMENT_REQUEST = 'DELETE_COMMENT_REQUEST';
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS';
export const DELETE_COMMENT_FAIL = 'DELETE_COMMENT_FAIL';
