export const GET_POST_ITEM_REQUEST = 'GET_POST_ITEM_REQUEST';
export const GET_POST_ITEM_SUCCESS = 'GET_POST_ITEM_SUCCESS';
export const GET_POST_ITEM_FAIL = 'GET_POST_ITEM_FAIL';
export const GET_POST_ITEM_RESET = 'GET_POST_ITEM_RESET';

export const GET_POSTS_REQUEST = 'GET_POSTS_REQUEST';
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const GET_POSTS_FAIL = 'GET_POSTS_FAIL';
export const GET_POSTS_RESET = 'GET_POSTS_RESET';

export const EDIT_POST_ITEM_REQUEST = 'EDIT_POST_ITEM_REQUEST';
export const EDIT_POST_ITEM_SUCCESS = 'EDIT_POST_ITEM_SUCCESS';
export const EDIT_POST_ITEM_FAIL = 'EDIT_POST_ITEM_FAIL';
export const EDIT_POST_ITEM_RESET = 'EDIT_POST_ITEM_RESET';

export const ADD_LIKE_POST_REQUEST = 'ADD_LIKE_POST_REQUEST';
export const ADD_LIKE_POST_SUCCESS = 'ADD_LIKE_POST_SUCCESS';
export const ADD_LIKE_POST_FAIL = 'ADD_LIKE_POST_FAIL';

export const REMOVE_LIKE_POST_REQUEST = 'REMOVE_LIKE_POST_REQUEST';
export const REMOVE_LIKE_POST_SUCCESS = 'REMOVE_LIKE_POST_SUCCESS';
export const REMOVE_LIKE_POST_FAIL = 'REMOVE_LIKE_POST_FAIL';

export const ADD_DISLIKE_POST_REQUEST = 'ADD_DISLIKE_POST_REQUEST';
export const ADD_DISLIKE_POST_SUCCESS = 'ADD_DISLIKE_POST_SUCCESS';
export const ADD_DISLIKE_POST_FAIL = 'ADD_DISLIKE_POST_FAIL';

export const REMOVE_DISLIKE_POST_REQUEST = 'REMOVE_DISLIKE_POST_REQUEST';
export const REMOVE_DISLIKE_POST_SUCCESS = 'REMOVE_DISLIKE_POST_SUCCESS';
export const REMOVE_DISLIKE_POST_FAIL = 'REMOVE_DISLIKE_POST_FAIL';

export const ADD_POST_REQUEST = 'ADD_POST_REQUEST';
export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS';
export const ADD_POST_FAIL = 'ADD_POST_FAIL';
export const ADD_COMMENT_RESET = 'ADD_COMMENT_RESET';

export const DELETE_POST_REQUEST = 'DELETE_POST_REQUEST';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const DELETE_POST_FAIL = 'DELETE_POST_FAIL';

export const ADD_COMMENT_REQUEST = 'ADD_COMMENT_REQUEST';
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';
export const ADD_COMMENT_FAIL = 'ADD_COMMENT_FAIL';

export const EDIT_COMMENT_REQUEST = 'EDIT_COMMENT_REQUEST';
export const EDIT_COMMENT_SUCCESS = 'EDIT_COMMENT_SUCCESS';
export const EDIT_COMMENT_FAIL = 'EDIT_COMMENT_FAIL';

export const DELETE_COMMENT_REQUEST = 'DELETE_COMMENT_REQUEST';
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS';
export const DELETE_COMMENT_FAIL = 'DELETE_COMMENT_FAIL';

export const ADD_LIKE_COMMENT_REQUEST = 'ADD_LIKE_COMMENT_REQUEST';
export const ADD_LIKE_COMMENT_SUCCESS = 'ADD_LIKE_COMMENT_SUCCESS';
export const ADD_LIKE_COMMENT_FAIL = 'ADD_LIKE_COMMENT_FAIL';

export const REMOVE_LIKE_COMMENT_REQUEST = 'REMOVE_LIKE_COMMENT_REQUEST';
export const REMOVE_LIKE_COMMENT_SUCCESS = 'REMOVE_LIKE_COMMENT_SUCCESS';
export const REMOVE_LIKE_COMMENT_FAIL = 'REMOVE_LIKE_COMMENT_FAIL';

export const ADD_DISLIKE_COMMENT_REQUEST = 'ADD_DISLIKE_COMMENT_REQUEST';
export const ADD_DISLIKE_COMMENT_SUCCESS = 'ADD_DISLIKE_COMMENT_SUCCESS';
export const ADD_DISLIKE_COMMENT_FAIL = 'ADD_DISLIKE_COMMENT_FAIL';

export const REMOVE_DISLIKE_COMMENT_REQUEST = 'REMOVE_DISLIKE_COMMENT_REQUEST';
export const REMOVE_DISLIKE_COMMENT_SUCCESS = 'REMOVE_DISLIKE_COMMENT_SUCCESS';
export const REMOVE_DISLIKE_COMMENT_FAIL = 'REMOVE_DISLIKE_COMMENT_FAIL';
