export const CREATE_PREMIUM_PACKAGE_REQUEST = 'CREATE_PREMIUM_PACKAGE_REQUEST';
export const CREATE_PREMIUM_PACKAGE_SUCCESS = 'CREATE_PREMIUM_PACKAGE_SUCCESS';
export const CREATE_PREMIUM_PACKAGE_FAIL = 'CREATE_PREMIUM_PACKAGE_FAIL';

export const UPDATE_PREMIUM_PACKAGE_REQUEST = 'UPDATE_PREMIUM_PACKAGE_REQUEST';
export const UPDATE_PREMIUM_PACKAGE_SUCCESS = 'UPDATE_PREMIUM_PACKAGE_SUCCESS';
export const UPDATE_PREMIUM_PACKAGE_FAIL = 'UPDATE_PREMIUM_PACKAGE_FAIL';

export const DELETE_PREMIUM_PACKAGE_REQUEST = 'DELETE_PREMIUM_PACKAGE_REQUEST';
export const DELETE_PREMIUM_PACKAGE_SUCCESS = 'DELETE_PREMIUM_PACKAGE_SUCCESS';
export const DELETE_PREMIUM_PACKAGE_FAIL = 'DELETE_PREMIUM_PACKAGE_FAIL';
