export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const USER_INFO_REQUEST = 'USER_INFO_REQUEST';
export const USER_INFO_SUCCESS = 'USER_INFO_SUCCESS';
export const USER_INFO_FAIL = 'USER_INFO_FAIL';
export const USER_INFO_RESET = 'USER_INFO_RESET';

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';
export const USER_UPDATE_RESET = 'USER_UPDATE_RESET';

export const USERS_LIST_REQUEST = 'USERS_LIST_REQUEST';
export const USERS_LIST_SUCCESS = 'USERS_LIST_SUCCESS';
export const USERS_LIST_FAIL = 'USERS_LIST_FAIL';
export const USERS_LIST_RESET = 'USERS_LIST_RESET';

export const USER_DELETE_REQUEST = 'USER_DELETE_REQUEST';
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS';
export const USER_DELETE_FAIL = 'USER_DELETE_FAIL';

export const ADMIN_GET_USER_INFO_REQUEST = 'ADMIN_GET_USER_INFO_REQUEST';
export const ADMIN_GET_USER_INFO_SUCCESS = 'ADMIN_GET_USER_INFO_SUCCESS';
export const ADMIN_GET_USER_INFO_FAIL = 'ADMIN_GET_USER_INFO_FAIL';

export const ADMIN_UPDATE_USER_REQUEST = 'ADMIN_UPDATE_USER_REQUEST';
export const ADMIN_UPDATE_USER_SUCCESS = 'ADMIN_UPDATE_USER_SUCCESS';
export const ADMIN_UPDATE_USER_FAIL = 'ADMIN_UPDATE_USER_FAIL';
export const ADMIN_UPDATE_USER_RESET = 'ADMIN_UPDATE_USER_RESET';

export const SET_USER_TO_PREMIUM_REQUEST = 'SET_USER_TO_PREMIUM_REQUEST';
export const SET_USER_TO_PREMIUM_SUCCESS = 'SET_USER_TO_PREMIUM_SUCCESS';
export const SET_USER_TO_PREMIUM_FAIL = 'SET_USER_TO_PREMIUM_FAIL';

export const CANCEL_USER_PREMIUM_REQUEST = 'CANCEL_USER_PREMIUM_REQUEST';
export const CANCEL_USER_PREMIUM_SUCCESS = 'CANCEL_USER_PREMIUM_SUCCESS';
export const CANCEL_USER_PREMIUM_FAIL = 'CANCEL_USER_PREMIUM_FAIL';

export const ADMIN_SET_USER_TO_PREMIUM_REQUEST =
  'ADMIN_SET_USER_TO_PREMIUM_REQUEST';
export const ADMIN_SET_USER_TO_PREMIUM_SUCCESS =
  'ADMIN_SET_USER_TO_PREMIUM_SUCCESS';
export const ADMIN_SET_USER_TO_PREMIUM_FAIL = 'ADMIN_SET_USER_TO_PREMIUM_FAIL';

export const ADMIN_CANCEL_USER_PREMIUM_REQUEST =
  'ADMIN_CANCEL_USER_PREMIUM_REQUEST';
export const ADMIN_CANCEL_USER_PREMIUM_SUCCESS =
  'ADMIN_CANCEL_USER_PREMIUM_SUCCESS';
export const ADMIN_CANCEL_USER_PREMIUM_FAIL = 'ADMIN_CANCEL_USER_PREMIUM_FAIL';
